default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 3306

development:
  <<: *default
  database: student_portal_development

test:
  <<: *default
  database: student_portal_test

production:
  <<: *default
  database: student_portal_production